version: '3.6'
services:
  mongo:
    image: mongo:4.0.10
    ports:
      - "27017:27017"
    networks:
      - erxes-net
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - erxes-net

  rabbitmq:
    image: rabbitmq:3.7.17-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - erxes-net
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

networks:
  erxes-net:
    driver: bridge

volumes:
  mongo_data:
  rabbitmq_data:
